name: dating_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  animate_do: ^2.0.0
  mrx_charts: ^0.1.3
  form_field_validator: ^1.1.0
  flutter_signin_button: ^2.0.0
  hexcolor: ^2.0.7
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  dio: ^4.0.6
  nearby_connections: ^3.2.0
  location: ^4.4.0
  firebase_database: ^9.1.4
  modal_progress_hud_nsn: ^0.3.0
  file_picker: ^5.0.1
  qr_code_scanner: ^1.0.1
  flutter_bluetooth_serial: ^0.3.2
  flutter_email_sender: ^5.2.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  firebase_storage: ^10.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
