name: Build and Upload

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: flutter/flutter-action@v23
      with:
        flutter-version: stable
        channel: master
        build-flavor: profile
    - uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: build/
