name: Build and Deploy iOS

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.3.9
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --debug --no-codesign
      - run: flutter build ios --simulator --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: build-ios
          path: build/ios
